### PR TITLE
Add Nautobot Feature

### LINKED ISSUE #178: support for Nautobot
### Proposed Functionality
* Implement support for Nautobot as source of truth.

### PR DESCRIPTION
**Pull request by jvanderaa**
## Fixes #178 

- Adds pynautobot to the required packages
- Creates Nautobot from NetBox data
- Removes versioning issues from NetBox
- Updates the HTTP Session creation, leveraging that within the pynautobot project

**WIP**

TODO:

- [x] Add pydantic configuration for Nautobot 
- [ ] Determine how to use which inventory (NetBox vs Nautobot) (@dgarros is working on)
- [x] Add tests (In progress by @jvanderaa)
- [x] Update pydantic settings
- [ ] Test on Nauatobot installation

### CODE REVIEW

**Comment by nniehoff** [comment]
@jvanderaa how's this one coming?

**Comment by jvanderaa** [comment]
Good. The next part is working on inventory. One complication is that the Nautobot Nornir inventory is Nornir 3.0. Damien is working on some updates there.

**Comment by jvanderaa** [comment]
I should close this one out in favor of the branch add_nautobot.

**Comment by jvanderaa** [comment]
Closing in favor of #206

**Pull request closed without merging**
